data:
  corpus: "../data/corpus.json"
  queries: "../data/queries.json"

llm_model: "meta-llama/Llama-3.3-70B-Instruct"
llm_base_url: "http://localhost:8000/v1"
embedding_model: "facebook/contriever"

retrieval:
  top_k: 5

output_dir: "../results"
